=== timko1106/xml1/src/xsd.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="genre" type="xs:string"/>
                            <xs:element name="year" type="xs:int"/>
                            <xs:element name="author" type="xs:string"/>

                        </xs:sequence>
                        <xs:attribute name="ID" type="xs:string" use="required"/>
                        <xs:attribute name="ISBN" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== timko1106/xml1/src/xml.xml
<?xml version="1.0" encoding="UTF-8"?>

<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
    <book ID="10000011001111110010110000111001101000001000001000100111010111011011100001" ISBN="110001111000110100110110">
        <name>граф де Монте Кристо</name>
        <genre>роман</genre>
        <year>1846</year>
        <author>А. Дюма</author>
    </book>
    <book ID="100001101001000011001010000110000100001101001000100011010000110000100010000101000100110010000010000010100100010011101000011110010000110000" ISBN="110001111000110111110000">
        <name>двадцать тысяч лье под водой</name>
        <genre>Научная фантастика</genre>
        <year>1870</year>
        <author>А. Дюма</author>
    </book>
    <book ID="100001101111000011000010000010000010100100010011101000011110010000110000" ISBN="110001111000110111110010">
        <name>за восемьдесят дней вокруг света</name>
        <genre>Приключенческая</genre>
        <year>1872</year>
        <author>А. Дюма</author>
    </book>
</library>
